const assert = require('node:assert')
;(async () => {
  const { site } = await import('../src/content/site.js')
  assert.ok(site.name === 'ZQW', 'name')
  assert.ok(site.nameZh === '张倩雯', 'nameZh')
  assert.ok(site.hero.kicker.includes('张倩雯 ZHANG QIANWEN'), 'kicker 含中文全名')
  assert.ok(site.hero.titleA.includes("Hi, I'm ZQW"), 'titleA')
  assert.ok(site.hero.titleB === 'Design beyond the interface.', 'titleB')
  assert.ok(site.hero.kicker.includes('UI/UX'), 'kicker 含 UI/UX')
  assert.ok(
    !site.hero.kicker.includes('DESIGNER') && !site.hero.kicker.includes('设计师'),
    'kicker 不写 DESIGNER / 设计师（避免夸大成熟度）'
  )
  assert.strictEqual(site.works.items.length, 3, 'works 3 件')
  assert.ok(site.works.items[0].title === '暖舍', 'works[0]')
  assert.ok(site.works.items[1].title === '卦了么', 'works[1]')
  assert.ok(site.works.items[2].titleEn === 'SPATIAL RENDER', 'works[2]')
  assert.strictEqual(site.lab.items.length, 4, 'lab 4 项')
  assert.strictEqual(site.capabilities.items.length, 4, 'capabilities 4 项')
  assert.ok(site.archive.items.length >= 6, 'archive >= 6')
  assert.ok(site.aboutMe.bio.length >= 2, 'aboutMe.bio 至少 2 段')
  assert.ok(site.aboutMe.bio[0].includes('张倩雯'), 'aboutMe 首段含名字')
  assert.ok(site.contact.methods.some((m) => m.label.includes('邮箱')), '有邮箱')
  assert.ok(site.contact.methods.some((m) => m.label.includes('微信')), '有微信')
  assert.ok(site.contact.methods.some((m) => m.label.includes('QQ')), '有 QQ')
  assert.ok(site.contact.methods.some((m) => m.label.includes('电话')), '有电话')
  assert.ok(site.nav.links.map((l) => l.id).join() === 'works,lab,about,contact,resume', 'nav 锚点')
  assert.ok(site.resume && typeof site.resume === 'object', 'resume 空结构存在')
  console.log('content check passed')
})().catch((e) => { console.error('content check failed:', e.message); process.exit(1) })
